name: flutter_event_bus_chat
description: Flutter Event Bus chat/message example
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0 # Or the latest version
  flutter_lints: ^6.0.0