name: 🤖 Flutter Android Apk

on:
  push:
    branches:
      - ci_cd_demo_android_apk_test
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout
      - name: 🛒 Checkout code
        uses: actions/checkout@v4


      # Step 3: Setup Flutter
      - name: 🧰 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      # Step 4: Install dependencies
      - name: 📦 Install dependencies
        run: flutter pub get

      # Step 5: build apk
      - name: Build APK
        run: flutter build apk --release

      # Step 6: create artifacts
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk