name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

jobs:
    build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: 'stable'
            channel: 'stable'

        - name: Get Dependencies
          run: flutter pub get
          working-directory: ./flutter_sample

        - name: Analyze and Test
          run: |
            flutter analyze
            flutter test
          working-directory: ./flutter_sample

        - name: Build Flutter Web
          run: flutter build web --release
          working-directory: ./flutter_sample

        - name: Deploy to Github Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            publish_dir: ./flutter_sample/build/web